---
environment:
    matrix:
    - TOXENV: check
    - TOXENV: spell
    - TOXENV: docs
    - TOXENV: safety
    - TOXENV: py37-cover
    - TOXENV: py37-nocov

build: off

install:
- pip install tox

test_script:
- tox
