# tox enviroments that run on both pull requests and merge to main
name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      # fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
        # you can separate the tox-envs in different .yml files
        # see version 0.10.1
        # https://github.com/joaomcteixeira/python-project-skeleton/releases/tag/v0.10.1
        # below the list of tox envs that you wish to include in the matrix
        tox-envs: [docs, lint, build, test]

    runs-on: pps

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install tox

    - name: unit tests
      run: tox -e ${{ matrix.tox-envs }}
