# taken and upgraded from:
# https://github.com/haddocking/pdb-tools/blob/f019d163d8f8cc5a0cba288e02f5a63a969719f6/.github/workflows/bump-version-on-push.yml
name: Bump_and_Package

on:
  push:
    branches:
      - master

jobs:
  bump-version:

    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[SKIP]')"

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Setup Git
      run: |
        git config user.name "joaomcteixeira"
        git config user.email 'joaomcteixeira@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"

    - name: Create skip flag
      run: |
        echo "SKIPBUMP=FALSE" >> $GITHUB_ENV

    - name: Create commit message
    - run: |
        echo ${{ github.event.head_commit.message }} >> $CMTMSG

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bump2version setuptools wheel twine

    - name: Bump Minor Version
      run: |
        bump2version minor
        echo "SKIPBUMP=TRUE" >> $GITHUB_ENV
      if: "startsWith(github.event.head_commit.message, '[FEATURE]')"

    # Default action
    - name: Bump Patch Version
      run: |
        bump2version --message '[SKIP] version bump {current_version} -> {new_version}\n\n{$CMTMSG}' patch
      if: env.SKIPBUMP == 'FALSE'

    # No major version change should go through automatically.

    - name: Commit version change to master
      run: |
        git push --follow-tags

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

